"""Add vehicle_type to ParkingSession

Revision ID: 2bb96affe928
Revises: 58036b3c07cf
Create Date: 2025-07-09 12:21:09.914093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb96affe928'
down_revision = '58036b3c07cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_sessions', schema=None) as batch_op:
        batch_op.drop_column('vehicle_type')

    # ### end Alembic commands ###
