"""tables update

Revision ID: 71f4f789416a
Revises: c898d0bb1299
Create Date: 2025-09-22 13:43:21.930248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f4f789416a'
down_revision = 'c898d0bb1299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_parking_lots', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'assigned_date',
                sa.Date(),
                nullable=False,
                server_default=sa.text('CURRENT_DATE')   # safe default for existing rows
            )
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_on')

    with op.batch_alter_table('admin_parking_lots', schema=None) as batch_op:
        batch_op.drop_column('assigned_date')

    # ### end Alembic commands ###
