"""add admin_payment_ledger table

Revision ID: 76aad77a380f
Revises: 2bb96affe928
Create Date: 2025-07-09 12:37:55.708876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76aad77a380f'
down_revision = '2bb96affe928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_payment_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=False),
    sa.Column('today_collection', sa.Float(), nullable=False),
    sa.Column('payment_made', sa.Float(), nullable=False),
    sa.Column('closing_balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id', 'date', name='uix_admin_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_payment_ledger')
    # ### end Alembic commands ###
