"""latest changes

Revision ID: c898d0bb1299
Revises: dd1f34a0812a
Create Date: 2025-09-18 13:41:36.841454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c898d0bb1299'
down_revision = 'dd1f34a0812a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parkinglots_details',
    sa.Column('parkinglot_id', sa.Integer(), nullable=False),
    sa.Column('parking_name', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('landmark', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('physical_appearance', sa.Text(), nullable=True),
    sa.Column('parking_ownership', sa.Text(), nullable=True),
    sa.Column('parking_surface', sa.Text(), nullable=True),
    sa.Column('has_cctv', sa.Text(), nullable=True),
    sa.Column('has_boom_barrier', sa.Text(), nullable=True),
    sa.Column('ticket_generated', sa.Text(), nullable=True),
    sa.Column('entry_exit_gates', sa.Text(), nullable=True),
    sa.Column('weekly_off', sa.Text(), nullable=True),
    sa.Column('parking_timing', sa.Text(), nullable=True),
    sa.Column('vehicle_types', sa.Text(), nullable=True),
    sa.Column('car_capacity', sa.Integer(), nullable=True),
    sa.Column('available_car_slots', sa.Integer(), nullable=True),
    sa.Column('two_wheeler_capacity', sa.Integer(), nullable=True),
    sa.Column('available_two_wheeler_slots', sa.Integer(), nullable=True),
    sa.Column('parking_type', sa.Text(), nullable=True),
    sa.Column('payment_modes', sa.Text(), nullable=True),
    sa.Column('car_parking_charge', sa.Text(), nullable=True),
    sa.Column('two_wheeler_parking_charge', sa.Text(), nullable=True),
    sa.Column('allows_prepaid_passes', sa.Text(), nullable=True),
    sa.Column('provides_valet_services', sa.Text(), nullable=True),
    sa.Column('value_added_services', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('parkinglot_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('user_password', sa.String(length=255), nullable=False),
    sa.Column('user_phone_no', sa.String(length=15), nullable=False),
    sa.Column('user_address', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_name'),
    sa.UniqueConstraint('user_phone_no')
    )
    op.create_table('admin_parking_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('parking_lot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['parkinglots_details.parkinglot_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_payment_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=False),
    sa.Column('today_collection', sa.Float(), nullable=False),
    sa.Column('payment_made', sa.Float(), nullable=False),
    sa.Column('closing_balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id', 'date', name='uix_admin_date')
    )
    op.create_table('floors',
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('floor_name', sa.String(length=50), nullable=False),
    sa.Column('parkinglot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parkinglot_id'], ['parkinglots_details.parkinglot_id'], ),
    sa.PrimaryKeyConstraint('floor_id')
    )
    op.create_table('rows',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('row_name', sa.String(length=50), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('parkinglot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.floor_id'], ),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_table('slots',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('slot_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('vehicle_reg_no', sa.String(length=20), nullable=True),
    sa.Column('ticket_id', sa.String(length=50), nullable=True),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('parkinglot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['row_id'], ['rows.row_id'], ),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_table('parking_sessions',
    sa.Column('ticket_id', sa.String(length=50), nullable=False),
    sa.Column('parkinglot_id', sa.Integer(), nullable=True),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_reg_no', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_hrs', sa.Numeric(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True),
    sa.Column('vehicle_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.slot_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parking_sessions')
    op.drop_table('slots')
    op.drop_table('rows')
    op.drop_table('floors')
    op.drop_table('admin_payment_ledger')
    op.drop_table('admin_parking_lots')
    op.drop_table('users')
    op.drop_table('parkinglots_details')
    # ### end Alembic commands ###
