"""Add admin_parking_lots table for admin-to-lot mapping

Revision ID: 58036b3c07cf
Revises: a370c6044e66
Create Date: 2025-07-09 11:04:58.422650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58036b3c07cf'
down_revision = 'a370c6044e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_parking_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('parking_lot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['parkinglots_details.parkinglot_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_parking_lots')
    # ### end Alembic commands ###
